// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkabjERh7w61Xm8jqr8Px56vQ6eP-k9BU',
    appId: '1:1081073558227:web:955b313269b21e10146a26',
    messagingSenderId: '1081073558227',
    projectId: 'random-c76ea',
    authDomain: 'random-c76ea.firebaseapp.com',
    storageBucket: 'random-c76ea.firebasestorage.app',
    measurementId: 'G-N69S08YZT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcNuFvuUORqKQv0GfU2HGwIJ58YLmxXNQ',
    appId: '1:1081073558227:android:8db8d50982a3f4a7146a26',
    messagingSenderId: '1081073558227',
    projectId: 'random-c76ea',
    storageBucket: 'random-c76ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IuhxIrqgn1YU51zxGU-KuF_2mreD15M',
    appId: '1:1081073558227:ios:e71ab98cbc18fe2b146a26',
    messagingSenderId: '1081073558227',
    projectId: 'random-c76ea',
    storageBucket: 'random-c76ea.firebasestorage.app',
    iosBundleId: 'com.example.random',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0IuhxIrqgn1YU51zxGU-KuF_2mreD15M',
    appId: '1:1081073558227:ios:e71ab98cbc18fe2b146a26',
    messagingSenderId: '1081073558227',
    projectId: 'random-c76ea',
    storageBucket: 'random-c76ea.firebasestorage.app',
    iosBundleId: 'com.example.random',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkabjERh7w61Xm8jqr8Px56vQ6eP-k9BU',
    appId: '1:1081073558227:web:64cb26780451de3a146a26',
    messagingSenderId: '1081073558227',
    projectId: 'random-c76ea',
    authDomain: 'random-c76ea.firebaseapp.com',
    storageBucket: 'random-c76ea.firebasestorage.app',
    measurementId: 'G-ZXJT30R1C5',
  );
}
